language: node_js

node_js:
  - "10"

cache:
  directories:
    - "$HOME/.sonar/cache"
    - "node_modules"
    - "coverage"
    - "build"

stages:
  - setup
  - audit
  - lint
  - test
  - sonar
  - build
  - deploy

jobs:
  include:
    - stage: setup
      script:
        - npm i
    - stage: audit
      script:
        - npm audit
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run coverage
    - stage: sonar
      script:
        - sonar-scanner
      addons:
        sonarcloud:
          token:
            secure: "$SONAR_API_KEY"
    - stage: build
      branches:
        only:
          - master
      script:
        - sed -i 's/<GIT_HASH>/$TRAVIS_COMMIT/g' src/lib/Version.ts
        - npm run build
    - stage: deploy
      branches:
        only:
          - master
      deploy:
        provider: lambda
        function_name: 'event-scheduler'
        region: '$AWS_REGION'
        role: '$AWS_LAMBDA_ROLE'
        handler_name: 'handler'
        runtime: 'nodejs10.x'
        zip: './build/index.zip'
